apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:latest
        command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
        env:
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8081"  # Optional: Set the Spark Worker web UI port
        ports:
          - containerPort: 8081

---

#apiVersion: v1
#kind: Pod
#metadata:
#  name: spark-master
#  labels:
#    app: spark-master
#spec:
#  containers:
#  - name: spark-master
#    image: bitnami/spark:latest
#    command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
#    ports:
#    - containerPort: 7077

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:latest
        command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
        ports:
        - containerPort: 7077
        - containerPort: 8080
        - containerPort: 6066
        - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  type: LoadBalancer
  selector:
    app: spark-master
  ports:
    - port: 80
      targetPort: 8080
      name: ui
    - port: 7077
      targetPort: 7077
      name: web
    - port: 6066
      targetPort: 6066
      name: uiweb
    - port: 443
      targetPort: 443
      name: sparksubmit

